### ISSUE TITLE
Sorry for opening a issue on this. I wanted to ask you about your partialzip-windows port to windows

### ISSUE THREAD

**Issue by goodboydheeraj** [sys-001/basic-pyro-bot#1]
I'm not able to download any files inside a remote zip/rar file. I'm getting these errors

C:\Users\USER\Desktop\partialzip-windows-master>partialzip.exe "http://updates-http.cdn-apple.com/2021SpringFCS/fullrestores/071-17697/00D910BB-FB55-49BD-80F5-33A3D73EF831/iPhone10,3,iPhone10,6_14.5_18E199_Restore.ipsw" BuildManifest.plist D:\
Initializing download for BuildManifest.plist...
      2 [main] partialzip 6552 cygwin_exception::open_stackdumpfile: Dumping stack trace to partialzip.exe.stackdump

and sometimes with a different path "partialzip.exe http://updates-http.cdn-apple.com/2021SpringFCS/fullrestores/071-17697/00D910BB-FB55-49BD-80F5-33A3D73EF831/iPhone10,3,iPhone10,6_14.5_18E199_Restore.ipsw BuildManifest.plist D:\BuildManifest.plist
Initializing download for BuildManifest.plist...
      6 [main] partialzip 4496 cygwin_exception::open_stackdumpfile: Dumping stack trace to partialzip.exe.stackdump

The stackdump is showing this
Exception: STATUS_ACCESS_VIOLATION at eip=00401515
eax=200910C5 ebx=00000000 ecx=00000000 edx=0000800E esi=0061CB80 edi=611D7DB2
ebp=0061C9D8 esp=0061C9C0 program=C:\Users\DHEERAJ\Desktop\partialzip-windows-master\partialzip.exe, pid 4496, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0061C9D8  00401515 (20050F80, 00000050, 00000001, 00000000)
0061CAE8  00401BD9 (0061CB90, 0061CC2B, 0061CD08, 66B36A22)
0061CB38  00402419 (00000004, 0061CB5C, 200280F0, 0061CB80)
0061CD08  61007A3F (00000000, 0061CD64, 61006A70, 00000000)
End of stack trace

and in this other instance (changed some url path to 1111... for anonymity)

C:\Users\USER\Desktop\partialzip-windows-master>partialzip.exe "http://sgp1.download.real-debrid.com/d/111111111111111/Spectre.2015.COMPLETE.UHD.BLURAY-COASTER.rar" "Spectre.2015.COMPLETE.UHD.BLURAY-COASTER/BDMV/STREAM/00029.m2ts" "D:/Spectre.2015.COMPLETE.UHD.BLURAY-COASTER"
Initializing download for \BDMV\STREAM\00029.m2ts...
Cannot find http://sgp1.download.real-debrid.com/d/1111111111111111/Spectre.2015.COMPLETE.UHD.BLURAY-COASTER.rar

Cannot find url error. Are rar files not supported?

I'm on Windows 10 20H2 Build 19042.844

**Comment by sys-001** [comment]
Hi, sorry for late response.
Anyway, I suggest you to compile and use [this new version](https://github.com/marcograss/partialzip), since the current build on my repo is really old (so, probably, even unreliable), you'll find the build instructions in the README.

Hope I helped you.
